baseURL = "http://aenrione.xyz/"
languageCode = "es-CL"
title = "Alfredo Enrione"
theme = "m10c"
staticDir = 'static'
# defaultContentLanguageInSubdir = true

defaultContentLanguage = "es"
[languages]
  [languages.en]
    languageName = "English"
    contentDir = "content/en"
    weight = 2
  [languages.es]
    languageName = "Español"
    contentDir = "content/es"
    weight = 1

[menu]
[[menu.main]]
identifier = "home"
name = "Inicio"
url = "/"
weight = 1
[[menu.main]]
identifier = "tags"
name = "Categorías"
url = "/tags/"
weight = 4
[[menu.main]]
identifier = "about"
name = "Acerca de mi"
url = "/about/"
weight = 3
[[menu.main]]
name = "Proyectos"
url = "/githubProjects/"
weight = 2
[[menu.main]]
name = "English Site"
url = "/en"
weight = 5

[[menu.en]]
identifier = "home"
name = "Home"
url = "/en"
weight = 1
[[menu.en]]
identifier = "tags"
name = "Tags"
url = "/en/tags/"
weight = 4
[[menu.en]]
identifier = "about"
name = "About"
url = "/en/about/"
weight = 3
[[menu.en]]
name = "Projects"
url = "/en/githubProjects/"
weight = 2
[[menu.en]]
name = "Sitio Español"
url = "/"
weight = 5

[params]
author = "Alfredo Enrione"
description = "Estudiante de ingenieria en computación"
descriptionEN = "Computer Engineer Student"
[[params.social]]
icon = "github"
name = "Github"
url = "https://github.com/aenrione"
[[params.social]]
icon = "mail"
name = "Email"
url = "mailto:aenrione@aenrione.xyz"
[[params.social]]
icon = "linkedin"
name = "Linkedin"
url = "https://www.linkedin.com/in/aenrione/"

# Default theme
[params.style]
darkestColor = "#242930"
darkColor = "#353b43"
lightColor = "#afbac4"
lightestColor = "#ffffff"
primaryColor = "#00bcd4"
